version: '3.7'

x-base-app: &base_app
  build:
    context: .
    dockerfile: Dockerfile
  entrypoint: ['sh', './entrypoint.sh']
  volumes:
      - ".:/app:cached"
      - bundle:/usr/local/bundle
  stdin_open: true
  tty: true
  tmpfs:
    - /tmp    
  env_file:
    - .env

services:
  page_views_api:
    <<: *base_app
    command: >
      bash -c "cron && whenever --set environment=$RACK_ENV --update-crontab && bundle exec puma --config config/puma.rb"
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mongodb
      - rabbitmq
      - sneakers

  mongodb:
    image: mongo
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - ${RABBITMQ_API_PORT}:${RABBITMQ_API_PORT}
    volumes:
      - "/data"
    env_file:
      - .env

  sneakers:
    <<: *base_app
    command: rake sneakers:run --trace
    depends_on:
      - rabbitmq


volumes:
  bundle:
  mongodb_data:

networks:
  default:
    external:
      name: dev_ntw