version: '3.7'

x-base-app: &base_app
  build:
    context: .
    dockerfile: Dockerfile
  entrypoint: ['sh', './entrypoint.sh']
  volumes:
      - ".:/app:cached"
      - bundle:/usr/local/bundle
  stdin_open: true
  tty: true
  tmpfs:
    - /tmp
  depends_on:
    - mongodb
  env_file:
    - .env

services:
  page_views_api:
    <<: *base_app
    command: >
      bash -c "bundle exec puma --config config/puma.rb"
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

  mongodb:
    image: mongo
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env

volumes:
  bundle:
  mongodb_data:

networks:
  default:
    external:
      name: dev_ntw